[package]
name = "geos"
version = "0.2.0"
authors = ["<matthieu.viry@cnrs.fr>", "Adrien Matissart <a.matissart@qwantresearch.com>", "Antoine Desbordes <antoine.desbordes@gmail.com"]
license = "MIT"
repository = "https://github.com/QwantResearch/rust-geos"

[dependencies]
libc = "*"
num = "*"
geo = ">=0.4,<=0.6"
failure = "0.1"
failure_derive = "0.1"
