[package]
name = "geos"
version = "4.1.0"
authors = ["Matthieu Viry <matthieu.viry@cnrs.fr>", "Adrien Matissart <a.matissart@qwantresearch.com>", "Antoine Desbordes <antoine.desbordes@gmail.com>", "Guillaume Pinot <texitoi@texitoi.eu>"]
license = "MIT"
repository = "https://github.com/georust/geos"
keywords = ["geos", "libgeos", "geometry", "geography", "gis"]
categories = ["external-ffi-bindings", "algorithms"]
description = "Rust bindings for GEOS C API"
readme = "README.md"
build = "build.rs"

[dependencies]
libc = "0.2"
num = "0.2"
geo-types = "0.4"
wkt = "0.5"
c_vec = "1.3"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
