[package]
name = "geos-src"
version = "0.1.0"
edition = "2018"
links = "geossrc"
build = "build.rs"
repository = "https://github.com/georust/geos"
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
license = "MIT"

[build-dependencies]
cmake = "0.1.45"
